# Generated by Django 4.2.7 on 2023-11-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_schoolprofile_id_alter_schoolprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa szkoły'),
        ),
    ]
