# Generated by Django 4.2.7 on 2023-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_schoolprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='lat',
            field=models.FloatField(default=0, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='long',
            field=models.FloatField(default=0, verbose_name='longitude'),
        ),
    ]
