# Generated by Django 4.2.7 on 2023-12-02 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_schoolprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='school_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
