# Generated by Django 4.2.7 on 2023-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfacility',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
