# Generated by Django 4.2.7 on 2023-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sportfacility_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfacility',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='building_number',
            field=models.PositiveIntegerField(verbose_name='numer budynku'),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='street_name',
            field=models.CharField(max_length=100, verbose_name='nazwa ulicy'),
        ),
    ]
