# Generated by Django 4.2.7 on 2023-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_reservation_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfacility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
